image: cschlosser/alpine-lftps
pipelines:
  branches:
    master:
      - step:
          deployment: production
          script:
            - lftp -d -e "mirror --reverse . $FTP_TARGET_PATH" -p $FTP_PORT -u $FTP_USERNAME,$FTP_PASSWORD $FTP_TARGET_SITE